sudo: required

services:
  - docker

script:
  - docker-compose run app

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  email: false
  slack:
    secure: aHM8iS573fA7sybR4/9f/au4ZiTusU1vYiVo1jRdJLDp72mQBVuhd5RDZ3p/+s13jRWoiVEBdZyv/UIMxK4RJ1mwPSn338VoWXzpXIyLdTApaPa5no59IFQ8egk+yXUdZeEnwBrLJRKQZNQw9NQKQg7AJcJUAwlhVLk4gu9oqCc5MnMwCnuWt5alPLujbwsn0vgP04BNVR4ZPxQTAZ2cBvJ20JaP/bAoOV/IhFlHIM3cfcWCwpVp6x9Zrmurwq70uJqyRrYoHIHo8+/nYDqkaXpLK6dGEcOyCugZs9j/vOcfts/+TIiJKeL6t85MOj7xd8DlfNo5PiRkJgIBDDJ20gZikuJAQC1VMurMQ0qnldumgaFfR6OeZS6ogh8SDS6iNpFwTdQeMUIbBFeQbB/p0BtRP/9SH5YYWvH1118dQGV+oxJtMDqm8gP37y8qE5wjw2TPM9RDHJ022RItf6+yeiYR44bKftsOQcSG8usbv3PtSCIl/NMlbfly1eYgrkD0bwod//qC3E3FybFkPZZC+KxHR4+yvw7Bfp32xNQCdlUiYc5gBbaatWEHZAEeln0p8LQ9HsTULXa/SByekoBYnI+BvOB4elZkvMfapxK1Zr2nzAa46zDLN1tOz1BAluoFKRS+S+fVm3+H+9Ia1PrWwN6tLwRuHri03KM+YC/j+Vk=
