app:
  build: .
  volumes:
      - .:/code
  working_dir: /code
  entrypoint: "./phpunit.sh"
  tty: true
  stdin_open: true
  links:
    - firebird
  environment:
    FIREBIRD_DB_DBNAME: firebird:/usr/local/firebird/examples/empbuild/employee.fdb
    FIREBIRD_DB_USER: SYSDBA
    FIREBIRD_DB_PASSWORD: masterkey

firebird:
  image: jacobalberty/firebird