version: "2"
services:
  app: &app
    build: .
    image: keboola/ex-db-firebird
    working_dir: /code
    command: composer ci
    environment:
      FIREBIRD_DB_DBNAME: firebird:/usr/local/firebird/examples/empbuild/employee.fdb
      FIREBIRD_DB_USER: SYSDBA
      FIREBIRD_DB_PASSWORD: pass
    links:
      - firebird
      - sshproxy

  dev:
    <<: *app
    image: keboola/ex-db-firebird-dev
    volumes:
      - ./:/code

  firebird:
    image: jacobalberty/firebird:2.5-sc
    environment:
      ISC_PASSWORD: pass

  sshproxy:
    image: keboola/db-component-ssh-proxy:latest
    ports:
      - "2222:22"
    links:
      - firebird
